version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENV=development
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  dashboard:
    build:
      context: .
      target: development
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENV=development
    command: python -m dashboard.app
    depends_on:
      - api

  tests:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: pytest tests/ --cov=./ --cov-report=xml

volumes:
  model_data: