apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-api
  labels:
    app: supply-chain-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: supply-chain-api
  template:
    metadata:
      labels:
        app: supply-chain-api
    spec:
      containers:
      - name: api
        image: ghcr.io/coop-columb/supply-chain-forecaster-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: supply-chain-api
spec:
  selector:
    app: supply-chain-api
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP