global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files to load
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["api-prod:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '$1'

  - job_name: "dashboard"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["dashboard-prod:8050"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '$1'

  - job_name: "node"
    static_configs:
      - targets: []