name: Model Deployment

on:
  workflow_dispatch:
    inputs:
      model_version:
        description: 'Model version to deploy'
        required: true
        default: 'latest'
  push:
    branches: [ main ]
    paths:
      - 'models/training/**'

jobs:
  evaluate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Evaluate model
      run: |
        python scripts/evaluate_model.py
        
    - name: Deploy model if evaluation passes
      run: |
        python scripts/deploy_model.py
        
    - name: Create model version tag
      if: success() && github.event_name == 'workflow_dispatch'
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        MODEL_VERSION=${{ github.event.inputs.model_version }}
        git tag -a "model-v${MODEL_VERSION}" -m "Model version ${MODEL_VERSION}"
        git push origin "model-v${MODEL_VERSION}"